Update patch set 1
Patch Set 1: Code-Review-1

> /home/vk/git/netconf-cli/src/netconf-client.cpp:10:10: fatal error: 'libyang/Tree_Data.hpp' file not found
> #include <libyang/Tree_Data.hpp>
>          ^~~~~~~~~~~~~~~~~~~~~~~
> /home/vk/git/netconf-cli/src/netconf_access.cpp:8:10: fatal error: 'libyang/Libyang.hpp' file not found
> #include <libyang/Libyang.hpp>
>          ^~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

This two are properly fixed by:

 target_link_libraries(netconfaccess PRIVATE PkgConfig::LIBYANG)

That's because this "requiring libyang" is an internal implementation detail of the "netconfaccess" target because nothing from libyang gets passed through any .hpp file from this lib.


> /home/vk/git/netconf-cli/src/yang_access.cpp:5:10: fatal error: 'libyang/Tree_Data.hpp' file not found
> #include <libyang/Tree_Data.hpp>
>          ^~~~~~~~~~~~~~~~~~~~~~~

 target_link_libraries(yangaccess PRIVATE PkgConfig::LIBYANG)

> /home/vk/git/netconf-cli/tests/datastore_access.cpp:10:10:         ^~~~~~~~~~~~~~~~~~~~~~~~~
>  fatal error: 'sysrepo-cpp/Session.hpp' file not found
> #include <sysrepo-cpp/Session.hpp>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~

This means that the fix in this change where you add linking to cmake's datastore_test_impl macro is correct. For the two errors above, though, these should IMHO be fixed by adding that PRIVATE linking with the library that provides the missing headers.

Patch-set: 1
Reviewer: Gerrit User 1000000 <1000000@e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68>
Label: Code-Review=-1