CI: coverage: don't break when multiple lambdas are used
The next patch triggers the following exception when running `gcovr`:

     raise AssertionError(
 AssertionError: Got function main::{lambda()#1}::operator()() const on multiple lines: 157, 214.
 	You can run gcovr with --merge-mode-functions=MERGE_MODE.
 	The available values for MERGE_MODE are described in the documentation.

These locations point to totally different lambdas. I suspect that
"something" doesn't properly understand lambda's name mangling, or
whatever. Anyway, let's use a big hammer and persuade `gcovr` that these
are, indeed, separate functions. I wonder what the other merge modes are
for...

Change-Id: I6acbb032324feee09dc8702e2010acbab0222cfe