Update patch set 2
Patch Set 2:

I think have a general idea about why the linking issues happen, it just hurts my brain to think about them properly...

Anyway: if I change to PRIVATE I get this:
In file included from /home/vk/git/netconf-cli/src/python_netconf.cpp:12:
/home/vk/git/netconf-cli/src/netconf-client.hpp:4:10: fatal error: libnetconf2/messages_client.h: No such file or directory
    4 | #include <libnetconf2/messages_client.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Patch-set: 2